import { Inter } from 'next/font/google'
import './globals.css'
import  Header  from './components/Header/Header'
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next auth CRUD app',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} bg-foreground text-background`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
